# Generated by Django 5.0.1 on 2024-03-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0002_currencyrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
