# Generated by Django 5.0.1 on 2024-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0003_delete_currencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс доллара')),
                ('eur_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс евро')),
                ('rub_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс рубля')),
                ('kzt_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс тенге')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Курсы валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
