# Generated by Django 5.0.1 on 2024-03-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0004_currencyexchangerates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyExchangeRates',
        ),
    ]
