# Generated by Django 5.0.1 on 2024-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0005_delete_currencyexchangerates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс доллара')),
                ('euro_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс евро')),
                ('tenge_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс тенге')),
                ('ruble_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс рубля')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
