# Generated by Django 5.0.1 on 2024-03-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0007_delete_currencyexchangerates'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс доллара')),
                ('euro_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс евро')),
                ('tenge_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс тенге')),
                ('ruble_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс рубля')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Курс валют',
            },
        ),
    ]
