# Generated by Django 5.0.1 on 2024-03-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0008_currencyexchangerates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyExchangeRates',
        ),
    ]
