# Generated by Django 5.0.1 on 2024-03-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0011_banner'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('header', 'Шапка'), ('main_top', 'Главная сверху'), ('main_bottom', 'Главная снизу'), ('aside', 'Боковая колонка')], max_length=20, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
