# Generated by Django 5.0.3 on 2024-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0012_alter_banner_clicks_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('main', 'Главная страница'), ('aside', 'Боковая колонка')], max_length=20, verbose_name='Позиция'),
        ),
    ]
