# Generated by Django 5.0.3 on 2024-08-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0014_otherlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherlinks',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть ссылку на сайте', verbose_name='Показать/Скрыть'),
        ),
        migrations.AlterField(
            model_name='otherlinks',
            name='image',
            field=models.ImageField(blank=True, help_text='400X150 или кратно этому', null=True, upload_to='other_links/', verbose_name='Изображение'),
        ),
    ]
