# Generated by Django 5.0.3 on 2024-08-31 04:01

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0016_partners'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressConferenceAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Дата и время пресс-конференции')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Название (описание)')),
            ],
            options={
                'verbose_name': 'Анонс пресс-конференции',
                'verbose_name_plural': 'Анонсы пресс-конференций',
            },
        ),
        migrations.CreateModel(
            name='PressConferenceAnnouncementsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Страница анонсов пресс-конференций',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PressConferenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя участника')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность участника')),
                ('announcement', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='simple_pages.pressconferenceannouncement')),
            ],
        ),
    ]
