# Generated by Django 5.0.1 on 2024-01-30 01:31

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='materials.author'),
        ),
    ]
