# Generated by Django 5.0.1 on 2024-01-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialpage_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
