# Generated by Django 5.0.1 on 2024-02-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialpage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialsindexpage',
            options={'verbose_name': 'Страница материалов'},
        ),
    ]
