# Generated by Django 5.0.1 on 2024-02-06 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_materialsindexpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpage',
            name='date',
        ),
        migrations.AddField(
            model_name='materialpage',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время публикации'),
        ),
    ]
