# Generated by Django 5.0.1 on 2024-02-19 02:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_remove_materialpage_date_materialpage_pub_date'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Страница категорий',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='materialpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='materials.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='materialpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='materialpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='materials.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='materialpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название'),
        ),
    ]
