# Generated by Django 5.0.1 on 2024-02-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_categorypage_alter_materialpage_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
