# Generated by Django 5.0.1 on 2024-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_searchresultspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResultsPage',
        ),
    ]
