# Generated by Django 5.0.1 on 2024-03-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_filterablematerialsindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterablematerialsindexpage',
            options={'verbose_name': 'Страница отфильтрованных материалов'},
        ),
    ]
