# Generated by Django 5.0.1 on 2024-03-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_filterablematerialsindexpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_basic',
            field=models.BooleanField(default=False, help_text='Если выбрать, категория будет отображаться в списке основных категорий', verbose_name='Основная категория'),
        ),
    ]
