# Generated by Django 5.0.1 on 2024-03-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_category_is_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Если выбрать, материал будет отображаться в разделе главных новостей, вверху главной страницы (3 последние материала с этой отметкой)', verbose_name='Главная новость'),
        ),
    ]
