# Generated by Django 5.0.1 on 2024-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_materialpage_video_file_materialpage_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='fb_video_url',
            field=models.URLField(blank=True, help_text='Добавьте ссылку на видео с Facebook', null=True, verbose_name='Ссылка на видео c Facebook'),
        ),
        migrations.AlterField(
            model_name='materialpage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Добавьте ссылку на видео с YouTube или Vimeo', null=True, verbose_name='Ссылка на видео с YouTube'),
        ),
    ]
