# Generated by Django 5.0.1 on 2024-03-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_materialpage_fb_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpage',
            name='video_file',
        ),
    ]
