# Generated by Django 5.0.1 on 2024-03-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_remove_materialpage_video_file'),
        # ('wagtailvideos', '0014_alter_videotrack_file_alter_videotrack_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='video_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
    ]
