# Generated by Django 5.0.1 on 2024-03-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_remove_materialpage_video_file'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='video_file',
            field=models.ForeignKey(blank=True, help_text='Загрузите видео-файл', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Видео-файл'),
        ),
    ]
