# Generated by Django 5.0.1 on 2024-03-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_remove_materialpage_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.author', verbose_name='Автор'),
        ),
    ]
