# Generated by Django 5.0.1 on 2024-03-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_materialpage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpage',
            name='categories',
        ),
    ]
