# Generated by Django 5.0.1 on 2024-03-21 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_remove_materialpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.category', verbose_name='Категория'),
        ),
    ]
