# Generated by Django 5.0.3 on 2024-08-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_materialpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
