# Generated by Django 5.0.3 on 2024-08-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_category_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
