# Generated by Django 5.0.3 on 2024-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_alter_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Если выбрать, материал будет отображаться в разделе важных новостей, вверху главной страницы рядом с главными', verbose_name='Важная новость'),
        ),
    ]
