# Generated by Django 5.0.3 on 2024-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_materialpage_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='No bio available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
