# Generated by Django 5.0.3 on 2024-08-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0030_author_bio_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='is_announcement',
            field=models.BooleanField(default=False, help_text='Выберите, если материал является анонсом', verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='materialpage',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Выберите, если материал посвящен текущей пресс-конференции', verbose_name='Live'),
        ),
        migrations.AddField(
            model_name='materialpage',
            name='is_survey',
            field=models.BooleanField(default=False, help_text='Выберите, если материал содержит опрос', verbose_name='Live'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
