# Generated by Django 5.0.3 on 2024-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0031_materialpage_is_announcement_materialpage_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='is_photo_report',
            field=models.BooleanField(default=False, help_text='Выберите, если материал содержит фоторепортаж. Этот материал попадет в секцию с фоторепортажами', verbose_name='Фоторепортаж'),
        ),
        migrations.AddField(
            model_name='materialpage',
            name='is_video_report',
            field=models.BooleanField(default=False, help_text='Выберите, если материал содержит видеорепортаж. Этот материал попадет в секцию с видеорепортажами', verbose_name='Видеорепортаж'),
        ),
        migrations.AlterField(
            model_name='materialpage',
            name='is_survey',
            field=models.BooleanField(default=False, help_text='Выберите, если материал содержит опрос', verbose_name='Опрос'),
        ),
    ]
