# Generated by Django 5.0.3 on 2024-08-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_regioncategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regioncategory',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='materialpage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.regioncategory', verbose_name='Регион'),
        ),
    ]
