# Generated by Django 5.0.3 on 2024-08-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_regioncategorypage_alter_materialpage_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='18X18', null=True, upload_to='authors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regioncategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
