# Generated by Django 5.0.3 on 2024-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0038_authorpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(help_text='18X18', upload_to='authors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
